# Generated by Django 5.1.15 on 2026-05-08 07:36

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('name', models.CharField(max_length=160, verbose_name="To'liq nomi")),
                ('short_name', models.CharField(max_length=120, verbose_name='Qisqa nomi')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('genre', models.CharField(blank=True, max_length=120, verbose_name='Janr')),
                ('founded', models.CharField(blank=True, max_length=16, verbose_name='Tashkil topgan yil')),
                ('directed_by', models.CharField(blank=True, max_length=160, verbose_name='Badiiy rahbar')),
                ('members_count', models.CharField(blank=True, max_length=120, verbose_name="A'zolar soni")),
                ('home_stage', models.CharField(blank=True, max_length=160, verbose_name='Asosiy sahna')),
                ('excerpt', models.TextField(blank=True, verbose_name="Qisqa ma'lumot")),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Rasm URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Rasm fayli')),
                ('body_html', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name="To'liq matn (richtext)")),
                ('body_blocks', models.JSONField(blank=True, default=list, editable=False)),
            ],
            options={
                'verbose_name': 'Ijodiy jamoa',
                'verbose_name_plural': 'Ijodiy jamoalar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
