# Generated by Django 5.1.15 on 2026-05-08 07:36

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('address_line1', models.CharField(default='Toshkent shahri, Mustaqillik maydoni 1-uy', max_length=255, verbose_name='Manzil 1-qator')),
                ('address_line2', models.CharField(default="100047, O'zbekiston Respublikasi", max_length=255, verbose_name='Manzil 2-qator')),
                ('map_embed_url', models.URLField(blank=True, default='https://www.openstreetmap.org/export/embed.html?bbox=69.2357%2C41.3070%2C69.2527%2C41.3170&layer=mapnik&marker=41.312000%2C69.244200', max_length=1000, verbose_name='Karta embed URL')),
                ('map_link', models.URLField(blank=True, default='https://www.openstreetmap.org/?mlat=41.312&mlon=69.2442#map=17/41.312/69.2442', max_length=1000, verbose_name='Karta havolasi')),
                ('latitude', models.FloatField(default=41.312, verbose_name='Kenglik')),
                ('longitude', models.FloatField(default=69.2442, verbose_name='Uzunlik')),
            ],
            options={
                'verbose_name': "Aloqa ma'lumotlari",
                'verbose_name_plural': "Aloqa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('full_name', models.CharField(max_length=120, verbose_name="To'liq ism")),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=160, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Mavzu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Murojaat mavzusi',
                'verbose_name_plural': 'Murojaat mavzulari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('image_url', models.URLField(blank=True, help_text='Yoki quyida fayl yuklang.', verbose_name='Rasm URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Rasm fayli')),
                ('subtext', models.CharField(max_length=255, verbose_name='Yuqori matn')),
                ('title', models.CharField(max_length=255, verbose_name='Asosiy sarlavha')),
            ],
            options={
                'verbose_name': 'Hero slayd',
                'verbose_name_plural': 'Hero slaydlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('name', models.CharField(max_length=120, verbose_name='Hamkor nomi')),
                ('image_url', models.CharField(blank=True, help_text='Public path yoki URL: /images/partners/ucell.png', max_length=500, verbose_name="Rasm URL/yo'l")),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Rasm fayli')),
                ('href', models.URLField(blank=True, verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('brand_full', models.CharField(default="O'zbekiston Davlat Filarmoniyasi Qashqadaryo viloyat bo'linmasi", max_length=255, verbose_name="Saytning to'liq nomi")),
                ('brand_short', models.CharField(default='Filarmoniya', max_length=120, verbose_name='Qisqa nom')),
                ('footer_address', models.CharField(default="Toshkent shahri, Navoiy ko'chasi, 2-uy", max_length=255, verbose_name='Footer manzili')),
                ('footer_phone', models.CharField(default='+998 71 234 56 78', max_length=64, verbose_name='Footer telefoni')),
                ('footer_email', models.EmailField(default='info@filarmoniya.uz', max_length=254, verbose_name='Footer e-mail')),
                ('copyright_line', models.CharField(default="© 2026 O'zbekiston Respublikasi Madaniyat Vazirligi. Barcha huquqlar himoyalangan.", max_length=255, verbose_name='Copyright satri')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ContactHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('days', models.CharField(max_length=120, verbose_name='Kunlar')),
                ('time', models.CharField(max_length=120, verbose_name='Soatlar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.contactinfo', verbose_name='Aloqa')),
            ],
            options={
                'verbose_name': 'Ish vaqti',
                'verbose_name_plural': 'Ish vaqti',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('label', models.CharField(max_length=120, verbose_name='Nomi')),
                ('value', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.contactinfo', verbose_name='Aloqa')),
            ],
            options={
                'verbose_name': 'E-mail manzili',
                'verbose_name_plural': 'E-mail manzillari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('label', models.CharField(max_length=120, verbose_name='Nomi')),
                ('value', models.CharField(max_length=64, verbose_name='Telefon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.contactinfo', verbose_name='Aloqa')),
            ],
            options={
                'verbose_name': 'Telefon raqami',
                'verbose_name_plural': 'Telefon raqamlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('platform', models.CharField(max_length=64, verbose_name='Platforma')),
                ('icon', models.CharField(help_text='Masalan: send, photo_camera, smart_display, public', max_length=64, verbose_name='Icon (Material Symbols)')),
                ('href', models.URLField(verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='core.contactinfo', verbose_name='Aloqa')),
            ],
            options={
                'verbose_name': 'Aloqa: ijtimoiy tarmoq',
                'verbose_name_plural': 'Aloqa: ijtimoiy tarmoqlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('label', models.CharField(max_length=120, verbose_name='Nomi')),
                ('href', models.CharField(default='#', help_text='Sayt ichida: /news, /about. Tashqi: https://...', max_length=255, verbose_name='Havola')),
                ('is_published', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationitem', verbose_name='Ota element')),
            ],
            options={
                'verbose_name': 'Navigatsiya elementi',
                'verbose_name_plural': 'Navigatsiya',
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('label', models.CharField(max_length=64, verbose_name='Nomi')),
                ('icon', models.CharField(help_text='masalan: telegram, instagram, facebook, youtube', max_length=64, verbose_name="Icon kalit so'zi")),
                ('href', models.URLField(verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='core.sitesettings', verbose_name='Sayt')),
            ],
            options={
                'verbose_name': 'Footer ijtimoiy havola',
                'verbose_name_plural': 'Footer ijtimoiy havolalar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
