# Generated by Django 5.1.15 on 2026-05-08 07:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('value', models.SlugField(max_length=64, unique=True, verbose_name='Qiymat')),
                ('label', models.CharField(max_length=120, verbose_name="Yorlig'i")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Tadbir kategoriyasi',
                'verbose_name_plural': 'Tadbir kategoriyalari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('date_value', models.CharField(help_text='Masalan: 24 yoki 05-08', max_length=32, verbose_name='Sana qiymati')),
                ('month', models.CharField(help_text='Masalan: OCT, NOV, DEC', max_length=12, verbose_name='Oy (qisqa)')),
                ('label', models.CharField(max_length=64, verbose_name="Yorlig'i (Main Hall, Chamber...)")),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Rasm URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Rasm fayli')),
                ('is_text_heavy', models.BooleanField(default=False, verbose_name='Matnga boy karta')),
            ],
            options={
                'verbose_name': 'Bosh sahifa tadbiri',
                'verbose_name_plural': 'Bosh sahifa tadbirlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AfishaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Qism sarlavhasi')),
                ('excerpt', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
                ('starts_at', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('venue', models.CharField(max_length=160, verbose_name='Joy')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Rasm URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='afisha/', verbose_name='Rasm fayli')),
                ('conductor', models.CharField(blank=True, max_length=200, verbose_name='Dirijyor / rejissor')),
                ('price', models.CharField(blank=True, max_length=120, verbose_name='Narx')),
                ('duration', models.CharField(blank=True, max_length=120, verbose_name='Davomiyligi')),
                ('about_html', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Tadbir haqida (richtext)')),
                ('about_blocks', models.JSONField(blank=True, default=list, editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Afisha tadbiri',
                'verbose_name_plural': 'Afisha tadbirlari',
                'ordering': ['starts_at'],
                'abstract': False,
            },
        ),
    ]
