# Generated by Django 5.1.15 on 2026-05-09 07:40

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_afishaevent_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Qism sarlavhasi')),
                ('excerpt', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
                ('starts_at', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('venue', models.CharField(max_length=160, verbose_name='Joy')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Rasm URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Rasm fayli')),
                ('conductor', models.CharField(blank=True, max_length=200, verbose_name='Dirijyor / rejissor')),
                ('price', models.CharField(blank=True, max_length=120, verbose_name='Narx')),
                ('duration', models.CharField(blank=True, max_length=120, verbose_name='Davomiyligi')),
                ('about_html', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Tadbir haqida (richtext)')),
                ('about_blocks', models.JSONField(blank=True, default=list, editable=False)),
                ('show_in_afisha', models.BooleanField(default=True, help_text="Yoqilgan bo'lsa, /afisha sahifasida ko'rinadi.", verbose_name="Afishada ko'rsatish")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['starts_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='afishaevent',
            name='category',
        ),
        migrations.DeleteModel(
            name='HomeEvent',
        ),
        migrations.DeleteModel(
            name='AfishaEvent',
        ),
    ]
