# Generated by Django 5.1.15 on 2026-05-08 07:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('hero_eyebrow', models.CharField(default='FILARMONIYA', max_length=120)),
                ('hero_title', models.CharField(default='Biz haqimizda', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True, max_length=1000)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('intro_title', models.CharField(default='Bir asrlik rezonans', max_length=200)),
                ('intro_body_html', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name="Kirish bo'limi matni")),
                ('intro_body_blocks', models.JSONField(blank=True, default=list, editable=False)),
                ('mission_title', models.CharField(default='Bizning missiya', max_length=200)),
                ('mission_text', models.TextField(blank=True)),
                ('leadership_title', models.CharField(default='Rahbariyat', max_length=200)),
                ('leadership_description', models.TextField(blank=True)),
                ('cta_title', models.CharField(default='Sahnamizga tashrif buyuring', max_length=200)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_primary_label', models.CharField(default="Afishani ko'rish", max_length=120)),
                ('cta_primary_href', models.CharField(default='/afisha', max_length=255)),
                ('cta_secondary_label', models.CharField(default="Biz bilan bog'lanish", max_length=120)),
                ('cta_secondary_href', models.CharField(default='/contact', max_length=255)),
            ],
            options={
                'verbose_name': 'Biz haqimizda sahifasi',
                'verbose_name_plural': 'Biz haqimizda sahifasi',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('code', models.CharField(max_length=16, verbose_name='ID (i, ii, iii...)')),
                ('number_label', models.CharField(max_length=64, verbose_name="Raqam yorlig'i (I bob)")),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bob',
                'verbose_name_plural': 'Boblar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChapteredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('kind', models.CharField(choices=[('statute', 'Muassasa nizomi'), ('youth_politics', 'Yoshlar siyosati')], max_length=32, unique=True, verbose_name='Hujjat turi')),
                ('eyebrow', models.CharField(default="Me'yoriy hujjatlar", max_length=120)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtitle')),
                ('approved_by', models.TextField(blank=True, verbose_name='Tasdiqlovchi')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name="E'lon qilingan sana")),
                ('document_number', models.CharField(blank=True, max_length=64, verbose_name='Hujjat raqami')),
            ],
            options={
                'verbose_name': "Bo'limlarga ajratilgan hujjat",
                'verbose_name_plural': "Bo'limlarga ajratilgan hujjatlar",
            },
        ),
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('year', models.CharField(max_length=16, verbose_name='Yil')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='pages.aboutpage')),
            ],
            options={
                'verbose_name': 'Tarixiy bosqich',
                'verbose_name_plural': 'Tarixiy bosqichlar',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='AboutLeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=160, verbose_name='Ism')),
                ('role', models.CharField(max_length=160, verbose_name='Lavozim')),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/leadership/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_members', to='pages.aboutpage')),
            ],
            options={
                'verbose_name': "Rahbariyat (about) a'zosi",
                'verbose_name_plural': "Rahbariyat (about) a'zolari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('value', models.CharField(max_length=64, verbose_name='Qiymat (85+, 320...)')),
                ('label', models.CharField(max_length=200, verbose_name="Yorlig'i")),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pages.aboutpage')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('number', models.CharField(max_length=16, verbose_name='Modda raqami')),
                ('intro', models.TextField(blank=True, verbose_name='Kirish jumlasi')),
                ('body_html', django_ckeditor_5.fields.CKEditor5Field(help_text='Har bir bandni alohida paragraf qilib yozing.', verbose_name='Modda matni (richtext)')),
                ('body_blocks', models.JSONField(blank=True, default=list, editable=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pages.chapter')),
            ],
            options={
                'verbose_name': 'Modda',
                'verbose_name_plural': 'Moddalar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='pages.chaptereddocument'),
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('label', models.CharField(max_length=255, verbose_name="Yorlig'i")),
                ('href', models.CharField(default='#', max_length=500, verbose_name='Havola')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('size', models.CharField(blank=True, max_length=64, verbose_name="Hajm yorlig'i")),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pages.chaptereddocument')),
            ],
            options={
                'verbose_name': 'Ilova',
                'verbose_name_plural': 'Ilovalar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
