# Generated by Django 5.1.15 on 2026-05-08 08:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='document',
        ),
        migrations.AddField(
            model_name='chaptereddocument',
            name='body_chapters',
            field=models.JSONField(blank=True, default=list, editable=False, verbose_name='Avtomatik bob/modda tuzilmasi'),
        ),
        migrations.AddField(
            model_name='chaptereddocument',
            name='body_html',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='<b>Bir maydonda butun hujjat.</b> <code>&lt;h2&gt;</code> sarlavhasi — bob (masalan: <i>I bob — Umumiy qoidalar</i>). <code>&lt;h3&gt;</code> sarlavhasi — modda (masalan: <i>1-modda</i>). Saqlanganda boblar va moddalar avtomatik ajratiladi.', verbose_name="To'liq matn (richtext)"),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
