# Generated by Django 5.1.15 on 2026-05-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_chapter_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_primary_href',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_primary_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_secondary_href',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_secondary_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='leadership_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='leadership_title',
        ),
        migrations.DeleteModel(
            name='AboutLeadershipMember',
        ),
    ]
