# Generated by Django 5.1.15 on 2026-05-08 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('value', models.SlugField(max_length=64, unique=True, verbose_name='Qiymat')),
                ('label', models.CharField(max_length=120, verbose_name="Yorlig'i")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Video kategoriyasi',
                'verbose_name_plural': 'Video kategoriyalari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('code', models.CharField(blank=True, help_text="Ichki identifikator. Bo'sh qoldirsangiz avtomatik shakllanadi.", max_length=32, unique=True, verbose_name='Kod (v-01)')),
                ('youtube_id', models.CharField(max_length=64, verbose_name='YouTube ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('duration', models.CharField(blank=True, max_length=32, verbose_name='Davomiyligi')),
                ('views_label', models.CharField(blank=True, max_length=32, verbose_name="Ko'rishlar yorlig'i")),
                ('date', models.DateField(verbose_name='Sana')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy video')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='media_app.videocategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
