# Generated by Django 5.1.15 on 2026-05-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text="To'liq YouTube havolasini joylang. Masalan: https://www.youtube.com/watch?v=fOk8Tm815lE yoki https://youtu.be/fOk8Tm815lE", max_length=500, verbose_name='YouTube havolasi'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='Havoladan avtomatik olinadi.', max_length=16, verbose_name='YouTube ID'),
        ),
    ]
