# Generated by Django 5.1.15 on 2026-05-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_video_youtube_url_alter_video_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='metadata_fetched_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Metadata olingan vaqt'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, editable=False, max_length=1000, verbose_name='YouTube thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(blank=True, help_text="Bo'sh qoldirsangiz YouTubedan olinadi.", null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, help_text="Bo'sh qoldirsangiz YouTubedan olinadi.", max_length=32, verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, help_text="Bo'sh qoldirsangiz YouTubedan olinadi.", max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views_label',
            field=models.CharField(blank=True, help_text="Bo'sh qoldirsangiz YouTubedan olinadi (masalan: 124K).", max_length=32, verbose_name="Ko'rishlar"),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text="To'liq YouTube havolasini joylang. Sarlavha, davomiylik, ko'rishlar va e'lon sanasi YouTubedan avtomatik olinadi.", max_length=500, verbose_name='YouTube havolasi'),
        ),
    ]
