# Generated by Django 5.1.15 on 2026-05-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_video_metadata_fetched_at_video_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name='Aktiv'),
        ),
    ]
