# Generated by Django 5.1.15 on 2026-05-08 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('name', models.CharField(max_length=300, verbose_name='Tanlov nomi')),
                ('year', models.CharField(max_length=8, verbose_name='Yil')),
                ('city', models.CharField(max_length=120, verbose_name='Shahar')),
                ('country', models.CharField(max_length=120, verbose_name='Davlat')),
                ('flag_code', models.CharField(blank=True, max_length=8, verbose_name='Bayroq kodi')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Xalqaro tanlov',
                'verbose_name_plural': 'Xalqaro tanlovlar',
                'ordering': ['-year', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntlConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('partner', models.CharField(max_length=200, verbose_name='Hamkor')),
                ('country', models.CharField(max_length=120, verbose_name='Davlat')),
                ('flag_code', models.CharField(blank=True, max_length=8, verbose_name='Bayroq kodi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('venue', models.CharField(max_length=200, verbose_name='Joy')),
                ('summary', models.TextField(verbose_name='Qisqacha bayon')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Rasm URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='intl_concerts/', verbose_name='Rasm fayli')),
            ],
            options={
                'verbose_name': "Qo'shma konsert",
                'verbose_name_plural': "Qo'shma konsertlar",
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('partner', models.CharField(max_length=200, verbose_name='Hamkor')),
                ('country', models.CharField(max_length=120, verbose_name='Davlat')),
                ('flag_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2: at, de, ru, kr, it, kz...', max_length=8, verbose_name='Bayroq kodi')),
                ('signed_at', models.DateField(verbose_name='Imzolangan sana')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('summary', models.TextField(verbose_name='Qisqacha bayon')),
                ('document_number', models.CharField(blank=True, max_length=64, verbose_name='Hujjat raqami')),
                ('file', models.FileField(blank=True, null=True, upload_to='memorandums/', verbose_name='Fayl')),
                ('external_url', models.CharField(blank=True, default='#', max_length=500, verbose_name='Tashqi havola')),
            ],
            options={
                'verbose_name': 'Memorandum',
                'verbose_name_plural': 'Memorandumlar',
                'ordering': ['-signed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionLaureate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('award', models.CharField(max_length=200, verbose_name='Mukofot')),
                ('order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laureates', to='international.competition')),
            ],
            options={
                'verbose_name': 'Laureat',
                'verbose_name_plural': 'Laureatlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
