# Generated by Django 5.1.15 on 2026-05-08 07:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=120, verbose_name='Ism familiya')),
                ('role', models.CharField(blank=True, max_length=160, verbose_name='Lavozim')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('published_at', models.DateField(verbose_name='Sana')),
                ('display_date', models.CharField(blank=True, help_text="Bo'sh qoldirsangiz Sanadan avtomatik shakllanadi (Oktabr 08, 2024).", max_length=64, verbose_name="Ko'rsatiladigan sana")),
                ('excerpt', models.TextField(verbose_name='Lid (qisqa tavsif)')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Hero rasm URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Hero rasm fayli')),
                ('body_html', django_ckeditor_5.fields.CKEditor5Field(help_text="Boy matn redaktoriga matn, surat, sitata yozing — sayt o'zi to'g'ri ko'rinishga keltiradi.", verbose_name="To'liq matn (richtext)")),
                ('body_blocks', models.JSONField(blank=True, default=list, editable=False, verbose_name='Avtomatik bloklar')),
                ('is_published', models.BooleanField(default=True, verbose_name="E'lon qilingan")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newsauthor', verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
