# Generated by Django 5.1.15 on 2026-05-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='author',
        ),
        migrations.DeleteModel(
            name='NewsAuthor',
        ),
    ]
