# Generated by Django 5.1.15 on 2026-05-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsarticle_author_delete_newsauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
