# Generated by Django 5.1.15 on 2026-05-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('type', models.CharField(max_length=120, verbose_name='Turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('document_number', models.CharField(blank=True, max_length=64, verbose_name='Hujjat raqami')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Fayl')),
                ('external_url', models.CharField(blank=True, default='#', max_length=500, verbose_name='Tashqi havola')),
                ('size', models.CharField(blank=True, help_text="Bo'sh qoldirilsa fayl hajmidan avtomatik hisoblanadi.", max_length=32, verbose_name='Hajm')),
                ('format', models.CharField(default='PDF', help_text='PDF, DOCX, XLSX, CSV...', max_length=16, verbose_name='Format')),
            ],
            options={
                'verbose_name': "Me'yoriy hujjat",
                'verbose_name_plural': "Me'yoriy hujjatlar",
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('type', models.CharField(max_length=120, verbose_name='Turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('document_number', models.CharField(blank=True, max_length=64, verbose_name='Hujjat raqami')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Fayl')),
                ('external_url', models.CharField(blank=True, default='#', max_length=500, verbose_name='Tashqi havola')),
                ('size', models.CharField(blank=True, help_text="Bo'sh qoldirilsa fayl hajmidan avtomatik hisoblanadi.", max_length=32, verbose_name='Hajm')),
                ('format', models.CharField(default='PDF', help_text='PDF, DOCX, XLSX, CSV...', max_length=16, verbose_name='Format')),
            ],
            options={
                'verbose_name': "Ochiq ma'lumot",
                'verbose_name_plural': "Ochiq ma'lumotlar",
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('type', models.CharField(max_length=120, verbose_name='Turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('document_number', models.CharField(blank=True, max_length=64, verbose_name='Hujjat raqami')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Fayl')),
                ('external_url', models.CharField(blank=True, default='#', max_length=500, verbose_name='Tashqi havola')),
                ('size', models.CharField(blank=True, help_text="Bo'sh qoldirilsa fayl hajmidan avtomatik hisoblanadi.", max_length=32, verbose_name='Hajm')),
                ('format', models.CharField(default='PDF', help_text='PDF, DOCX, XLSX, CSV...', max_length=16, verbose_name='Format')),
            ],
            options={
                'verbose_name': 'Press-reliz',
                'verbose_name_plural': 'Press-relizlar',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
