# Generated by Django 5.1.15 on 2026-05-08 07:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name="Bo'lim nomi")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_published', models.BooleanField(default=True, help_text="Faqat yoqilgan yozuvlar saytda ko'rinadi.", verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, help_text="Past raqamlar avval ko'rsatiladi.", verbose_name='Tartib raqami')),
                ('group', models.CharField(choices=[('management', 'Rahbariyat'), ('central_apparatus', 'Markaziy apparat')], default='central_apparatus', max_length=32, verbose_name="Bo'linma turi")),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('fullname', models.CharField(max_length=160, verbose_name="To'liq ism familiya")),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Qabul vaqti / Ish jadvali')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Rasm URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='people/', verbose_name='Rasm fayli')),
                ('description_html', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Biografiya (richtext)')),
                ('description_blocks', models.JSONField(blank=True, default=list, editable=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='people.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('platform', models.CharField(max_length=64, verbose_name='Platforma')),
                ('href', models.URLField(verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='people.person', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Xodim ijtimoiy havolasi',
                'verbose_name_plural': 'Xodim ijtimoiy havolalari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
