export const documentsMeta = {
  eyebrow: "Me'yoriy hujjatlar",
  title: "Me'yoriy hujjatlar",
  description:
    "Filarmoniya faoliyatini tartibga soluvchi qonunlar, qarorlar va boshqa rasmiy hujjatlar to'plami.",
  category: 'documents',
};

export const documents = [
  {
    id: 1,
    title: "O'zbekiston Respublikasining 'Madaniyat to'g'risida'gi Qonuni",
    type: 'Qonun',
    date: '2023-06-14',
    size: '420 KB',
    format: 'PDF',
    documentNumber: "O'RQ-842",
    url: '#',
  },
  {
    id: 2,
    title:
      "O'zbekiston Respublikasi Prezidentining 'Filarmoniya va konsert tashkilotlari faoliyatini takomillashtirish to'g'risida'gi Qarori",
    type: 'Prezident qarori',
    date: '2023-02-17',
    size: '680 KB',
    format: 'PDF',
    documentNumber: 'PQ-3813',
    url: '#',
  },
  {
    id: 3,
    title: "O'zbekiston Davlat Filarmoniyasi Qashqadaryo viloyat bo'linmasi Nizomi",
    type: 'Nizom',
    date: '2023-05-02',
    size: '312 KB',
    format: 'PDF',
    documentNumber: 'NZ-015',
    url: '#',
  },
  {
    id: 4,
    title: "Vazirlar Mahkamasining 'Ijodiy xodimlar ish haqi to'g'risida'gi Qarori",
    type: 'VM qarori',
    date: '2024-01-22',
    size: '245 KB',
    format: 'PDF',
    documentNumber: 'VMQ-44',
    url: '#',
  },
  {
    id: 5,
    title: "Ichki mehnat tartibi qoidalari",
    type: 'Ichki hujjat',
    date: '2024-03-10',
    size: '180 KB',
    format: 'DOCX',
    documentNumber: 'ITQ-2024',
    url: '#',
  },
  {
    id: 6,
    title: "Korrupsiyaga qarshi kurashish siyosati",
    type: 'Ichki hujjat',
    date: '2023-09-18',
    size: '156 KB',
    format: 'PDF',
    documentNumber: 'AK-009',
    url: '#',
  },
  {
    id: 7,
    title: "Axborot xavfsizligi va shaxsiy ma'lumotlarni himoya qilish reglamenti",
    type: 'Ichki hujjat',
    date: '2024-02-05',
    size: '290 KB',
    format: 'PDF',
    documentNumber: 'AXR-12',
    url: '#',
  },
  {
    id: 8,
    title: "Xodimlarni attestatsiyadan o'tkazish tartibi",
    type: 'Buyruq',
    date: '2024-04-12',
    size: '210 KB',
    format: 'PDF',
    documentNumber: 'B-178',
    url: '#',
  },
  {
    id: 9,
    title: "Jamoaviy shartnoma",
    type: 'Ichki hujjat',
    date: '2024-01-15',
    size: '520 KB',
    format: 'PDF',
    documentNumber: 'JS-2024',
    url: '#',
  },
  {
    id: 10,
    title: "Madaniy tadbirlar rejasi (2024-2025 mavsum)",
    type: 'Reja',
    date: '2024-08-30',
    size: '1.2 MB',
    format: 'PDF',
    documentNumber: 'MR-2024-25',
    url: '#',
  },
];
